export const team_member_info = [
	{
		name: 'Julie Antonio',
		role: 'Project Leader',
		img_path: 'julie.jfif',
		link_title: 'LINK_TEXT',
		link_url: 'LINK_URL',
		bio: 'BIO',
	},
	{
		name: 'Jordan Doan',
		role: 'Backend Developer',
		img_path: 'jordan.png',
		link_title: 'website',
		link_url: 'http://jordan-doan.com/',
		bio: 'i like chimkin nunget',
	},
	{
		name: 'Mark King',
		role: 'Backend Developer',
		img_path: 'mark.jfif',
		link_title: 'LINK_TEXT',
		link_url: 'LINK_URL',
		bio: 'BIO',
	},
	{
		name: 'Ryan Ziegenfus',
		role: 'Backend Developer',
		img_path: 'ryan.jfif',
		link_title: 'LINK_TEXT',
		link_url: 'LINK_URL',
		bio: 'BIO',
	},
	{
		name: 'Faye Skeen',
		role: 'Frontend Developer',
		img_path: 'faye.jfif',
		link_title: 'LINK_TEXT',
		link_url: 'LINK_URL',
		bio: 'BIO',
	},
	{
		name: 'Jonathan Ho',
		role: 'Frontend Developer',
		img_path: 'jonathan.jfif',
		link_title: 'LinkedIn',
		link_url: 'https://www.linkedin.com/in/jonathan-y-ho/',
		bio: 'BIO',
	},
	{
		name: 'Krishan Nattar',
		role: 'Frontend Developer',
		img_path: 'krishan.jfif',
		link_title: 'Do it',
		link_url: 'http://krishannattar.com/',
		bio: 'Choose me to live happily ever after. With little to no cannibalism.',
	},
	{
		name: 'Nick Gonzalez',
		role: 'Frontend Developer',
		img_path: 'nick.jfif',
		link_title: 'LINK_TEXT',
		link_url: 'LINK_URL',
		bio: 'BIO',
	},
	{
		name: 'Jan Meiiii!',
		role: 'Stakeholder',
		img_path: 'janmei.jpg',
		link_title: 'Explore quality!',
		link_url: 'https://explorequality.com',
		bio: 'Just a simple quail living my best quail life',
	},
];
