export const team_member_info = [
	{
		name: 'Julie Antonio',
		role: 'Project Leader',
		img_url: 'julie.jfif',
		link_title: 'LINK_TEXT',
		link_url: '_url_URL',
		bio: 'BIO',
	},
	{
		name: 'Jordan Doan',
		role: 'Backend Developer',
		img_url: 'jordan.png',
		link_title: 'LINK_TEXT',
		link_url: 'LINK_URL',
		bio: 'BIO',
	},
	{
		name: 'Mark King',
		role: 'Backend Developer',
		img_url: 'mark.jfif',
		link_title: 'LINK_TEXT',
		link_url: 'LINK_URL',
		bio: 'BIO',
	},
	{
		name: 'Ryan Ziegenfus',
		role: 'Backend Developer',
		img_url: 'ryan.jfif',
		link_title: 'LINK_TEXT',
		link_url: 'LINK_URL',
		bio: 'BIO',
	},
	{
		name: 'Faye Skeen',
		role: 'Frontend Developer',
		img_url: 'faye.jfif',
		link_title: 'LINK_TEXT',
		link_url: 'LINK_URL',
		bio: 'BIO',
	},
	{
		name: 'Jonathan Ho',
		role: 'Frontend Developer',
		img_url: 'jonathan.jfif',
		link_title: 'LINK_TEXT',
		link_url: 'LINK_URL',
		bio: 'BIO',
	},
	{
		name: 'Krishan Nattar',
		role: 'Frontend Developer',
		img_url: 'krishan.jfif',
		link_title: 'LINK_TEXT',
		link_url: 'LINK_URL',
		bio: 'BIO',
	},
	{
		name: 'Nick Gonzalez',
		role: 'Frontend Developer',
		img_url: 'nick.jfif',
		link_title: 'LINK_TEXT',
		link_url: 'LINK_URL',
		bio: 'BIO',
	},
	{
		name: 'Jan Mei',
		role: 'Stakeholder',
		img_url: '',
		link_title: 'LINK_TEXT',
		link_url: 'LINK_URL',
		bio: 'BIO',
	},
];
