export const team_member_info = [
	{
		name: 'Juliette Antoniou',
		role: 'Project Leader',
		img_path: 'julie.jfif',
		link_title: 'GitHub',
		link_url: 'https://github.com/julieantonio',
		bio: 'Web22 | Labs18 QualityHub+InterviewQ',
	},
	{
		name: 'Jordan Doan',
		role: 'Backend Developer',
		img_path: 'jordan.png',
		link_title: 'website',
		link_url: 'http://jordan-doan.com/',
		bio: 'i like chimkin nunget',
	},
	{
		name: 'Mark King',
		role: 'Backend Developer',
		img_path: 'mark.jfif',
		link_title: 'GitHub',
		link_url: 'https://github.com/markpkng',
		bio: 'Web 23 | Labs19 | Community Calendar',
	},
	{
		name: 'Ryan Ziegenfus',
		role: 'Backend Developer',
		img_path: 'ryan.jfif',
		link_title: 'GitHub',
		link_url: 'https://github.com/ryanZiegenfus',
		bio: 'Web22 | Labs18 QualityHub+InterviewQ',
	},
	{
		name: 'Faye Skeen',
		role: 'Frontend Developer',
		img_path: 'faye.jfif',
		link_title: 'GitHub',
		link_url: 'https://github.com/fskeen',
		bio: 'International person of mystery; also, web dev.',
	},
	{
		name: 'Jonathan Ho',
		role: 'Frontend Developer',
		img_path: 'Jonathan.jpg',
		link_title: 'LinkedIn',
		link_url: 'https://www.linkedin.com/in/jonathan-y-ho/',
		bio: 'Web22 | Labs18 QualityHub+InterviewQ',
	},
	{
		name: 'Krishan Nattar',
		role: 'Frontend Developer',
		img_path: 'krishan.jfif',
		link_title: 'Do it',
		link_url: 'http://krishannattar.com/',
		bio: `Mommy's good boy!!!`,
	},
	{
		name: 'Nick Gonzalez',
		role: 'Frontend Developer',
		img_path: 'nick.jfif',
		link_title: 'GitHub',
		link_url: 'https://github.com/NickGonzalez04',
		bio: 'Web22 | Labs18 QualityHub+InterviewQ',
	},
	{
		name: 'Jan Meiiii!',
		role: 'Stakeholder',
		img_path: 'janmei.jpg',
		link_title: 'Explore quality!',
		link_url: 'https://explorequality.com',
		bio: 'Just a simple quail living my best quail life',
	},
];
